name: gg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py310h06a4308_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - click=8.1.7=py310h06a4308_0
  - fastapi=0.103.0=py310h06a4308_0
  - h11=0.12.0=pyhd3eb1b0_0
  - idna=3.4=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - pydantic=1.10.12=py310h5eee18b_1
  - python=3.10.13=h955ad1f_0
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sniffio=1.2.0=py310h06a4308_1
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - typing-extensions=4.7.1=py310h06a4308_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023d=h04d1e81_0
  - uvicorn=0.25.0=py310hff52083_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - cachecontrol==0.13.1
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cryptography==41.0.7
      - firebase==4.0.1
      - firebase-admin==6.3.0
      - google-api-core==2.15.0
      - google-api-python-client==2.113.0
      - google-auth==2.26.2
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.1
      - google-cloud-firestore==2.14.0
      - google-cloud-storage==2.14.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.62.0
      - grpcio==1.60.0
      - grpcio-status==1.60.0
      - httplib2==0.22.0
      - msgpack==1.0.7
      - proto-plus==1.23.0
      - protobuf==4.25.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - requests==2.31.0
      - rsa==4.9
      - uritemplate==4.1.1
      - urllib3==2.1.0
prefix: /home/biggergig/miniconda3/envs/gg
